### PR TITLE
Rebuild for openssl3

### PR DESCRIPTION
**Pull request by h-vetinari**
Migrator says it's awaiting parents, but no remaining parents have rstudio as a child. 🤔

### CODE REVIEW

**Comment by h-vetinari** [comment]
Blocked on https://github.com/conda-forge/qt-webengine-feedstock/pull/15

**Comment by h-vetinari** [comment]
~Now  blocked on https://github.com/conda-forge/qt-webengine-feedstock/pull/19~

That's not the case...

**Comment by h-vetinari** [comment]
@izahn 
Can you remind me why we pinned to `nodejs 14`? I cannot find it in the [blame](https://github.com/izahn/staged-recipes/blame/da4386de47dde7aee254a5dcda91d969f6a6c692/recipes/rstudio-desktop/meta.yaml) of the feedstock or even the staged recipes [PR](https://github.com/conda-forge/staged-recipes/pull/18320).

**Comment by h-vetinari** [comment]
Ah, since the PR for openssl 3 on qt-main brought in postgres 15, this now needs https://github.com/conda-forge/soci-feedstock/pull/12

**Comment by h-vetinari** [comment]
> Can you remind me why we pinned to `nodejs 14`? I cannot find it in the [blame](https://github.com/izahn/staged-recipes/blame/da4386de47dde7aee254a5dcda91d969f6a6c692/recipes/rstudio-desktop/meta.yaml) of the feedstock or even the staged recipes [PR](https://github.com/conda-forge/staged-recipes/pull/18320).

It looks like node 14 is [incompatible](https://github.com/conda-forge/nodejs-feedstock/pull/242) with openssl3; we'd need to move to 16 and/or 18.

**Comment by izahn** [comment]
> > Can you remind me why we pinned to `nodejs 14`? I cannot find it in the [blame](https://github.com/izahn/staged-recipes/blame/da4386de47dde7aee254a5dcda91d969f6a6c692/recipes/rstudio-desktop/meta.yaml) of the feedstock or even the staged recipes [PR](https://github.com/conda-forge/staged-recipes/pull/18320).
> 
> It looks like node 14 is [incompatible](https://github.com/conda-forge/nodejs-feedstock/pull/242) with openssl3; we'd need to move to 16 and/or 18.

Simply because at the time I wrote the recipe that was the version upstream used for their builds. That has now changed as shown in https://github.com/rstudio/rstudio/blob/7edcdeb2b4ab510a206fb408bcf21f8b6cfa7d5c/dependencies/tools/rstudio-tools.sh#L471 so we can an should go to nodejs 16.

**Comment by h-vetinari** [comment]
> Simply because at the time I wrote the recipe that was the version upstream used for their builds. That has now changed as shown in https://github.com/rstudio/rstudio/blob/7edcdeb2b4ab510a206fb408bcf21f8b6cfa7d5c/dependencies/tools/rstudio-tools.sh#L471 so we can an should go to nodejs 16.

OK cool. Any reason IYO not to _also_ build for nodejs 18?

**Comment by h-vetinari** [comment]
@izahn PTAL (not least w.r.t. nodejs versions) :)

**Comment by izahn** [comment]
Looks good to me! Cool to see the nodejs 18 builds pass, big 👍🏽

**Pull request merged**
